name: cross-sensor-cal
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - pyarrow
  - h5py
  - requests
  - tqdm
  - matplotlib
  - rasterio=1.3.*
  - gdal=3.8.*
  - shapely=2.*
  - geopandas=0.14.*
  - pip:
      - spectral
      - ray[default]>=2.2
